/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/home2`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/profile-pic`; params?: Router.UnknownInputParams; } | { pathname: `/reset-password`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/verify-email`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/BackButton`; params?: Router.UnknownInputParams; } | { pathname: `/components/CountryPickerModal`; params?: Router.UnknownInputParams; } | { pathname: `/components/CustomCamera`; params?: Router.UnknownInputParams; } | { pathname: `/components/CustomGallery`; params?: Router.UnknownInputParams; } | { pathname: `/components/EmailOrPhoneInput`; params?: Router.UnknownInputParams; } | { pathname: `/components/new`; params?: Router.UnknownInputParams; } | { pathname: `/components/new2`; params?: Router.UnknownInputParams; } | { pathname: `/constants/constants`; params?: Router.UnknownInputParams; } | { pathname: `/svgs/SVG`; params?: Router.UnknownInputParams; } | { pathname: `/utils/ToastDesign`; params?: Router.UnknownInputParams; } | { pathname: `/utils/validateEmail`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/forgot-password`; params?: Router.UnknownOutputParams; } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/home2`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/profile-pic`; params?: Router.UnknownOutputParams; } | { pathname: `/reset-password`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/verify-email`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/BackButton`; params?: Router.UnknownOutputParams; } | { pathname: `/components/CountryPickerModal`; params?: Router.UnknownOutputParams; } | { pathname: `/components/CustomCamera`; params?: Router.UnknownOutputParams; } | { pathname: `/components/CustomGallery`; params?: Router.UnknownOutputParams; } | { pathname: `/components/EmailOrPhoneInput`; params?: Router.UnknownOutputParams; } | { pathname: `/components/new`; params?: Router.UnknownOutputParams; } | { pathname: `/components/new2`; params?: Router.UnknownOutputParams; } | { pathname: `/constants/constants`; params?: Router.UnknownOutputParams; } | { pathname: `/svgs/SVG`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/ToastDesign`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/validateEmail`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/forgot-password${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/home2${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/profile-pic${`?${string}` | `#${string}` | ''}` | `/reset-password${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/verify-email${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/BackButton${`?${string}` | `#${string}` | ''}` | `/components/CountryPickerModal${`?${string}` | `#${string}` | ''}` | `/components/CustomCamera${`?${string}` | `#${string}` | ''}` | `/components/CustomGallery${`?${string}` | `#${string}` | ''}` | `/components/EmailOrPhoneInput${`?${string}` | `#${string}` | ''}` | `/components/new${`?${string}` | `#${string}` | ''}` | `/components/new2${`?${string}` | `#${string}` | ''}` | `/constants/constants${`?${string}` | `#${string}` | ''}` | `/svgs/SVG${`?${string}` | `#${string}` | ''}` | `/utils/ToastDesign${`?${string}` | `#${string}` | ''}` | `/utils/validateEmail${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/home2`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/profile-pic`; params?: Router.UnknownInputParams; } | { pathname: `/reset-password`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/verify-email`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/BackButton`; params?: Router.UnknownInputParams; } | { pathname: `/components/CountryPickerModal`; params?: Router.UnknownInputParams; } | { pathname: `/components/CustomCamera`; params?: Router.UnknownInputParams; } | { pathname: `/components/CustomGallery`; params?: Router.UnknownInputParams; } | { pathname: `/components/EmailOrPhoneInput`; params?: Router.UnknownInputParams; } | { pathname: `/components/new`; params?: Router.UnknownInputParams; } | { pathname: `/components/new2`; params?: Router.UnknownInputParams; } | { pathname: `/constants/constants`; params?: Router.UnknownInputParams; } | { pathname: `/svgs/SVG`; params?: Router.UnknownInputParams; } | { pathname: `/utils/ToastDesign`; params?: Router.UnknownInputParams; } | { pathname: `/utils/validateEmail`; params?: Router.UnknownInputParams; };
    }
  }
}
